version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14

  pre_build:
    commands:
      - npm install -g htmlhint stylelint

  build:
    commands:
      - htmlhint index.html
      - stylelint styles.css
      - npm run lint  # Assuming you have a linting script in your package.json

artifacts:
  files:
    - favi.png
    - headshot.JPG
    - index.html
    - scripts.js
    - styles.css
